### ISSUE TITLE
Motivation post

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/Ace#76]
Call for Assistance

why Ace
why Raxx

Plans
- Raxx on cowboy (new stream handlers)
- Ace design is to push purity so can be checked by session types
- Integration with APNS GRPC graphql

**Comment by CrowdHailer** [comment]
This looks like it will instead be a conf talk but I will try and write it up as well

**Comment by sashaafm** [comment]
Can you also compare against Phoenix? I think that's a question many people have when they see this project. 

Also 👍 for session types. Good stuff.

**Comment by CrowdHailer** [comment]
I will think about how to do that. Though I try not too go to far down the vs route. There won't be a database layer to compare for starters. Also I think the complexity of plug + phoenix is self evident once you look under the covers but for anyone who is happy for convenience in preference to simplicity that is their choice

**Comment by nietaki** [comment]
Some comparison might be worth it, to give people looking at it an idea what it does and what it doesn't give you. So probably stating that Ace is not competing with Phoenix, but comparing it to Plug and raw cowboy would be useful.

**Comment by CrowdHailer** [comment]
@sashaafm If you are looking for more of an answer. It all follows from thinking of HTTP as message passing rather than a conn that is written to/ read from. That lead to Raxx https://github.com/crowdhailer/raxx#getting-started the rest mostly just follows from there

**Comment by CrowdHailer** [comment]
@sashaafm This is a post I have written to explain why raxx. http://crowdhailer.me/2018-02-23/http-is-message-passing/

**Comment by CrowdHailer** [comment]
covered by posted blog articlle and elixir daze talk

**Comment by Pjino** [comment]
Hi. I'm looking into Ace/Raxx and I was thinking about trying it as a replacement for Phoenix/Plug that were very good to help me start with Elixir Web apps, but not anymore. Nevertheless, you said that "There won't be a database layer to compare for starters". Ok. I agree. But could you share pragmatic examples of using a database? Otherwise that could be a stopper for now for someone like me that came from the front-end and databases (although working with PostgreSQL) are not something that I care about a lot and as such I'm very interested in some simplicity over that interface.
Do you think you'll do anything soon to guide/simplify over there?
Thanks!

**Comment by CrowdHailer** [comment]
Hi @Pjino I don't have any public examples with database access setup. However I have used Ecto with Raxx and the docs in Ecto are easy to follow. There's really no reason web and db concerns need to be conflated and using Ecto in a Raxx app doesn't present any problems.

The interface might have a couple of extra charachters now and again but updating a model is simple and explicit
```elixir
{:ok, params} = URI.decode_www_form(request.body)
MyModel.changeset(%MyModel{}, params)
```
If you want to ask around for help try the #raxx channel on elixir slack
https://elixir-lang.slack.com/messages/C56H3TBH8/?

**Comment by Pjino** [comment]
Hi @CrowdHailer Thank you! So, this means we can go with Ecto! Ok. I'm using Ecto Myself, but as the purpose of this change would be to stay "pure" I didn't know your opinion on Ecto. Nevertheless, I suggest you to add just a few lines about using Ecto with Raxx so that it become clear that that's the way to go (and then, every Phoenix user knows Ecto).
GREAT work!
PS: Let me say (for truthiness sake) that when you started this 2 years ago I though you were just trying to "piss those guys off a little" with some small details. But now...I understand your point and share your view. I'm glad you didn't quit it!

**Comment by CrowdHailer** [comment]
@Pjino I'll think about adding something about Ecto, might make more sense in a blog post than a README. There is no correction between Raxx and Ecto but you are right it might be a special case because of everyones familiarity with Ecto

Yeah it has taken a little while for me to work out how to explain well what I'm up to. I'm glad you've come around for another look
